### ISSUE TITLE
Can we have a synchronous wrapper?

### ISSUE THREAD

**Issue by isthisstackoverflow** [padlet/async-math#1]
There's some cases where I'd like to work with these functions synchronously, since my promise stack is seriously getting through the roof. I know I could just use async/await, but I'd have to rewrite that everywhere. So please offer a synchronous wrapper?

Maybe a second module, like async-math-sync, would come in handy.

**Comment by coffeebite** [comment]
Synchronous programming is against best practices. Closing this for now.
